/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface DogList {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLDogListElement extends Components.DogList, HTMLStencilElement {
    }
    var HTMLDogListElement: {
        prototype: HTMLDogListElement;
        new (): HTMLDogListElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "dog-list": HTMLDogListElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface DogList {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "dog-list": DogList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "dog-list": LocalJSX.DogList & JSXBase.HTMLAttributes<HTMLDogListElement>;
        }
    }
}
